### ISSUE TITLE
ffmpeg on windows 

### ISSUE THREAD

**Issue by MesterPerfect** [ThorpeJosh/ffmpeg-gui#5]
hi
I have a file ffmpeg.exe
In which path should this file be placed in order for the ffmpeg-gui library to work
When I try to run it on Windows
---------------------------
Error
---------------------------
FFMPEG is not installed
Macos: 'brew install ffmpeg'
Linux: 'apt-get install ffmpeg'
Windows: You're on your own
---------------------------
OK   
---------------------------

**Comment by ThorpeJosh** [comment]
Hey, thanks for trying out this app.

You can put the exe anywhere in your PATH, but I would highly recommend using a package manager rather than downloading files off the internet and manually installing them.

Try chocolatey for windows:
```
choco install ffmpeg
```

**Comment by ThorpeJosh** [comment]
I have updated the error message to be more helpful for windows and other linux distros.

https://github.com/ThorpeJosh/ffmpeg-gui/commit/0df5ec5c51e053e4c6bb4979bd79bf8ef3b621ba
